# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8118a417f0458316d66b83aa46cb0e6e8163df21fae0cee7280ba1abd4946bbafbf468283d511b5458e7b6aa84e279bddcb5c6343c0c36e70df7735148eaf4

test:
  secret_key_base: 8311483fa303e28e15c043aa62e754417ee791cbdb1bcf6d59f7191559c1839943ed78be05f0dc0d4ad03be9b9506dd393f700e1c0ddcb19b8a4fd5212bba8b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
